Created DAL for shipping confirmation
pgd-harmeet/wsi-triggers pull request #8
Opened 2023-11-30 19:46 UTC by tyler-golfdiscount

- Created a method for retrieving shipping confirmations
- Created two methods for inserting shipping confirmations
- Used those two insertion methods inside a method to insert the shipping confirmations
- Made a namespace in the Models for shipping confirmations
- inside included a ShippingConfirmationModel and a ShippingConfirmationDetailModel

2023-11-30 20:22 UTC, pgd-harmeet requested changes
There are some small issues with commenting, consistent method signatures, and error handling. These are shown by comments on a per-file basis.

2023-11-30 20:22 UTC, pgd-harmeet commented on Data/ShippingConfirmations.cs
> +        /// <param name="conn">Open SqlConnection to the WSI database</param>
This parameter does not match the method signature.

2023-11-30 20:22 UTC, pgd-harmeet commented on Data/ShippingConfirmations.cs
> +                };
Your data model in `Pgd.Wsi.Models.ShippingConfirmation` specifies a `ShipDate` and a `ShippingMethod` property which is not in the SQL query above or during your object assignment.

2023-11-30 20:22 UTC, pgd-harmeet commented on Data/ShippingConfirmations.cs
> +                    throw new ArgumentException("Pickticket number cannot be found in database");
Annotate that this exception is being thrown in your method comment.

2023-11-30 20:22 UTC, pgd-harmeet commented on Data/ShippingConfirmations.cs
> +            cmd.CommandText = @"INSERT INTO [shipping_confirmation] (line_number, sku, units)
The `sku` and `units` field do not exist in the target table `shipping_confirmation` in the database.

2023-11-30 20:22 UTC, pgd-harmeet commented on Data/ShippingConfirmations.cs
> +            using SqlCommand cmd = conn.CreateCommand();
Wrap in a `try-catch-finally` block for error handling.

2023-11-30 20:22 UTC, pgd-harmeet commented on Data/ShippingConfirmations.cs
> +            using SqlCommand cmd = conn.CreateCommand();
Wrap in a `try-catch-finally block.`

2023-11-30 20:22 UTC, pgd-harmeet commented on Data/PickTicket.cs
> +                ShippingConfirmationModel confirmation = ShippingConfirmations.GetShippingConfirmation(header.PickTicketNumber, connString);
The `ShippingConfirmations.GetShippingConfirmation`  method throws an exception which you have not caught. This will bubble up causing calls below the stack to fail.

2023-11-30 20:22 UTC, pgd-harmeet commented on Data/PickTicket.cs
> +                ShippingConfirmationModel confirmation = ShippingConfirmations.GetShippingConfirmation(header.PickTicketNumber, connString);
The `ShippingConfirmations.GetShippingConfirmation` method throws an exception which you have not caught. This will bubble up causing calls below the stack to fail.

2023-11-30 20:22 UTC, pgd-harmeet commented on Data/PickTicket.cs
> +                    ShippingConfirmationModel confirmation = ShippingConfirmations.GetShippingConfirmation(header.PickTicketNumber, connString);
The `ShippingConfirmations.GetShippingConfirmation` method throws an exception which you have not caught. This will bubble up causing calls below the stack to fail.

2023-11-30 20:22 UTC, pgd-harmeet commented on HttpTriggers/PickTickets.cs
> +                PickTicketModel pickTicket = PickTicket.GetPickTicket(pickTicketNumber, _cs);
Extra whitespace

2023-11-30 20:41 UTC, tyler-golfdiscount commented on Data/ShippingConfirmations.cs
> +            cmd.CommandText = @"INSERT INTO [shipping_confirmation] (line_number, sku, units)
The `sku` and `units` field are in the dev database and not in the staging database. I'll add those to staging.

2023-12-06 18:54 UTC, pgd-harmeet commented on Data/ShippingConfirmations.cs
> +        /// <exception cref="Exception">All operations around this method are surrounded by a transaction which rollbacked if an exception is encountered, commited otherwise.</exception>
Where is this exception being thrown? Your comment indicates that this method throws the generate `Exception` type but it is not thrown in this method. You only want to document the exceptions that your functionality throws.

2024-01-04 06:04 UTC, closed without merging